//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel_Product
    {
        public int Id { get; set; }
        public Nullable<int> Carousel_id { get; set; }
        public Nullable<int> Prod_id { get; set; }
        public string Prod_name { get; set; }
        public Nullable<int> Prod_category { get; set; }
        public Nullable<int> Prod_subcategory { get; set; }
        public Nullable<int> status { get; set; }
    }
}
