//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public long category_id { get; set; }
        public string category_name { get; set; }
        public string category_type { get; set; }
        public int status { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modify_date { get; set; }
    }
}
