//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_address
    {
        public decimal id { get; set; }
        public int user_id { get; set; }
        public string customer_name { get; set; }
        public string customer_address1 { get; set; }
        public string customer_city { get; set; }
        public string customer_area { get; set; }
        public string customer_country { get; set; }
        public Nullable<int> customer_pincode { get; set; }
        public int customer_mobile { get; set; }
        public int address_status { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
