//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string order_no { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> payment_status { get; set; }
        public Nullable<int> shipment_status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> address_id { get; set; }
    }
}
