//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_order
    {
        public int id { get; set; }
        public string basket_session { get; set; }
        public Nullable<int> show_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> pay_status { get; set; }
        public string cancel_reason { get; set; }
        public string shipping_notes { get; set; }
        public Nullable<int> delivery_boy_id { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<System.DateTime> Confirmed_date { get; set; }
        public Nullable<System.DateTime> packed_date { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public Nullable<System.DateTime> delivered_date { get; set; }
        public Nullable<System.DateTime> cancelled_date { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
    }
}
