//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_order_list
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> product_item_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<decimal> product_amount_sell { get; set; }
        public Nullable<decimal> product_amount_mrp { get; set; }
        public Nullable<int> order_list_status { get; set; }
        public string product_details { get; set; }
        public string product_category { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<decimal> product_total_amount { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
    }
}
