//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuyDirectApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public long Id { get; set; }
        public Nullable<int> prod_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> wish_status { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
    }
}
